version: "3.9"

services: 
  go_db:
    container_name: go_db
    image: mysql:8.0  
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
      MYSQL_USER: ${MYSQL_USER}  
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  
      MYSQL_DATABASE: $MYSQL_DATABASE}  
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql  

volumes:
  mysql_data: {}
